name: fetch API data

on:
  schedule:
    - cron: 30 12 * * 4 # At 12:30 every Thursday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: get_date
        # run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_GH_actions.txt
          
      - name: execute py script
        run: |
          python API_pull_data.py

      - name: update kaggle dataset
        # env:
        #   # Do not leak your credentials.
        #   KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        #   KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |

          # cd data/kaggle
          # kaggle datasets metadata albertovidalrod/electricity-consumption-uk-20092022
          # kaggle datasets version -m "Data update ${{ steps.get_date.outputs.date}}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Data update ${{ steps.get_date.outputs.date}}"
          git push
